dataset:
  name: "UCI Bike Sharing Dataset"
  source_url: "https://archive.ics.uci.edu/static/public/275/bike+sharing+dataset.zip"
  sha256: "b70182d0d0508e9abbb79306ce5c0cec34869000f8220175ac83d11dbe845401"
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  splitted_dir: "data/splitted"
  zip_filename: "bike_sharing_dataset.zip"
  dataset_dirname: "bike_sharing_dataset"

files:
  hourly_csv: "hour.csv"
  daily_csv: "day.csv"
  train_hourly_csv: "train_hourly.csv"
  test_hourly_csv: "test_hourly.csv"
  train_daily_csv: "train_daily.csv"
  test_daily_csv: "test_daily.csv"
